### ISSUE TITLE
Getting order items details

### ISSUE THREAD

**Issue by hajsf** [tulir/whatsmeow#111] opened 2022-05-01 12:56 UTC
Hi, I was able to read received order as below: 

```go
	id := evt.Message.OrderMessage.OrderId
	itemCount := evt.Message.OrderMessage.ItemCount
	message := evt.Message.OrderMessage.Message
```

This is reading the order details, how can I  read the detailed lines inside this order, i.e. items and their quantities.

**Comment by hrizal** [comment] 2022-05-01 21:53
tryng as @Romerito007 suggested, but it doesn't work 😅 #21 


```
func (cli *Client) GetOrderdetails(orderId, token string) (*waBinary.Node, error) {
	orderNode, err := cli.sendIQ(infoQuery{
		Namespace: "fb:thrift_iq",
		Type:      "get",
		To: types.ServerJID,
		ID: "5",
		Content: []waBinary.Node{
				{
					Tag: "order",
					Attrs:  waBinary.Attrs{
						"op": "get",
						"id": orderId,
					},
				},
				{
					Tag:     "token",
					Content: []byte(token),
				},
				{
					Tag: "image_dimensions",
					Content: []waBinary.Node{
						{
							Tag:     "width",
							Content: []byte("100"),
						}, {
							Tag:     "height",
							Content: []byte("100"),
						},
					},
				},
			},
	})
	return orderNode, err
```}

**Comment by Romerito007** [comment] 2022-05-04 02:22
Function to fetch product catalog and order item details. Add smax_id properties in infoQuery struct

```
func (cli *Client) GetCatalog(jid types.JID, limit int) (*waBinary.Node, error) {
	catalogNode, err := cli.sendIQ(infoQuery{
		Namespace: "w:biz:catalog",
		Type:      "get",
		To:        types.ServerJID,
		Content: []waBinary.Node{
			{
				Tag: "product_catalog",
				Attrs: waBinary.Attrs{
					"jid":               jid,
					"allow_shop_source": true,
				},
				Content: []waBinary.Node{
					{
						Tag:     "limit",
						Attrs:   nil,
						Content: []byte("10"),
					},
					{
						Tag:     "width",
						Attrs:   nil,
						Content: []byte("100"),
					}, {
						Tag:     "height",
						Attrs:   nil,
						Content: []byte("100"),
					},
				},
			},
		},
	})
	fmt.Println(catalogNode.XMLString())
	return catalogNode, err
}
```
````
func (cli *Client) GetOrderDetails(id, orderId, tokenBase64 string) (*waBinary.Node, error) {
	detailsNode, err := cli.sendIQ(infoQuery{
		Namespace: "fb:thrift_iq",
		Type:      "get",
		To:        types.ServerJID,
		SmaxId:    id,
		Content: []waBinary.Node{
			{
				Tag: "order",
				Attrs: waBinary.Attrs{
					"op": "get",
					"id": orderId,
				},
				Content: []waBinary.Node{
					{
						Tag:   "image_dimensions",
						Attrs: nil,
						Content: []waBinary.Node{
							{
								Tag:     "width",
								Attrs:   nil,
								Content: []byte("100"),
							}, {
								Tag:     "height",
								Attrs:   nil,
								Content: []byte("100"),
							},
						},
					},
					{
						Tag:     "token",
						Attrs:   nil,
						Content: []byte(tokenBase64),
					},
				},
			},
		},
	})
	fmt.Println(detailsNode.XMLString())
	return detailsNode, err
}
````

**Comment by hajsf** [comment] 2022-05-04 08:09
> Add smax_id properties in infoQuery struct

Did not get your point here!

**Comment by hajsf** [comment] 2022-05-04 09:01
> Function to fetch product catalog and order item details.

I tried:
```go
package whatsmeow

import (
	"fmt"

	waBinary "go.mau.fi/whatsmeow/binary"
	"go.mau.fi/whatsmeow/types"
)

func (cli *Client) GetOrderDetails(id, orderId, tokenBase64 string) (*waBinary.Node, error) {
	detailsNode, err := cli.sendIQ(infoQuery{
		Namespace: "fb:thrift_iq",
		Type:      "get",
		To:        types.ServerJID,
		SmaxId:    id,
		Content: []waBinary.Node{
			{
				Tag: "order",
				Attrs: waBinary.Attrs{
					"op": "get",
					"id": orderId,
				},
				Content: []waBinary.Node{
					{
						Tag:   "image_dimensions",
						Attrs: nil,
						Content: []waBinary.Node{
							{
								Tag:     "width",
								Attrs:   nil,
								Content: []byte("100"),
							}, {
								Tag:     "height",
								Attrs:   nil,
								Content: []byte("100"),
							},
						},
					},
					{
						Tag:     "token",
						Attrs:   nil,
						Content: []byte(tokenBase64),
					},
				},
			},
		},
	})
	fmt.Println(detailsNode.XMLString())
	return detailsNode, err
}
```
And called it as:
```go
	case *events.Message:
		id := *evt.Message.OrderMessage.OrderId
		token := *evt.Message.OrderMessage.Token

		fmt.Println("id:", id, "token:", token)

		details, err := global.Cli.GetOrderDetails("1", id, *evt.Message.OrderMessage.Token)
		if err != nil {
			fmt.Println("Error:", err)
		} else {
			fmt.Println(*details)
		}
```
But got nothing:
<img width="517" alt="image" src="https://user-images.githubusercontent.com/98168280/166651772-e128ef36-b815-42d2-95a0-c0d2fb2fd066.png">

**Comment by tulir** [comment] 2022-05-04 09:03
Duplicate of #21

**Closed by tulir** 2022-05-04 09:03 UTC
