### ISSUE TITLE
Getting first message

### ISSUE THREAD

**Issue by 1337-sys** [tulir/whatsmeow#251] opened 2022-09-23 10:23 UTC
Hi @tulir,

Sometimes the first message does not come. What would be the reason?  Could this problem have something to do with sending ack immediately (E057347129E155279DBE6A7DA114BBA7 - Below details)?

Voice and missed call received but first message not received. 

![telegram-cloud-photo-size-4-5868711083999607040-y](https://user-images.githubusercontent.com/75783166/191939515-928c585a-f6dc-4e12-a55e-b107a7a818c3.jpg)

```
17:40:50.628 [Client/Recv DEBUG] <message from="19148****@s.whatsapp.net" id="E057347129E155279DBE6A7DA114BBA7" notify="*MaskedPushName**" t="1663868450" type="text"><url_text/><url_number/><unavailable/></message>
17:40:50.628 [Client WARN] Unavailable message E057347129E155279DBE6A7DA114BBA7 from 19148****@s.whatsapp.net
17:40:50.628 [Client/Send DEBUG] <ack class="message" id="E057347129E155279DBE6A7DA114BBA7" to="19148****@s.whatsapp.net"/>
17:40:50.630 [Client DEBUG] Push name of 19148****@s.whatsapp.net changed from  to *MaskedPushName**, dispatching event
time="2022-09-22T17:40:50.630713147Z" level=info msg="[HandlePushName] event: (*events.PushName)(0xc01358fe60)({\n JID: (types.JID) 19148****@s.whatsapp.net,\n Message: (*types.MessageInfo)(0xc019420120)({\n  MessageSource: (types.MessageSource) {\n   Chat: (types.JID) 19148****@s.whatsapp.net,\n   Sender: (types.JID) 19148****@s.whatsapp.net,\n   IsFromMe: (bool) false,\n   IsGroup: (bool) false,\n   BroadcastListOwner: (types.JID) \n  },\n  ID: (string) (len=32) \"E057347129E155279DBE6A7DA114BBA7\",\n  Type: (string) \"\",\n  PushName: (string) (len=16) \"*MaskedPushName**\",\n  Timestamp: (time.Time) 2022-09-22 17:40:50 +0000 UTC,\n  Category: (string) \"\",\n  Multicast: (bool) false,\n  MediaType: (string) \"\",\n  DeviceSentMeta: (*types.DeviceSentMeta)(<nil>)\n }),\n OldPushName: (string) \"\",\n NewPushName: (string) (len=16) \"*MaskedPushName**\"\n})\n\n" func="/opt/whatsapp-md/pkg/service.(*WP).HandlePushName" file="/opt/whatsapp-md/pkg/service/events.go:232"
17:40:50.631 [Client/Send DEBUG] <receipt id="E057347129E155279DBE6A7DA114BBA7" to="19148****@s.whatsapp.net" type="retry"><retry count="1" id="E057347129E155279DBE6A7DA114BBA7" t="1663868450" v="1"/><registration>4dc80cf9</registration><keys><type>05</type><identity>2f669da1823aa7d3adec9d500f40cbd886e7ae95196c8ef4e028b77f4f8ffe59</identity><key><id>000355</id><value>cae3fa8047bcc42e1db4df7eedb90b9f12026a8ef0e1357b29621462bedd0a40</value></key><skey><id>000001</id><value>ad7f08788e20cb412064ed537b1ef57b23846c949d78397798e29173687a566e</value><signature>efba23fe898185183d62d66073aaa0fbb6d7ee274f511248583f6d5ee27b6878d21b69952493a770980c961c435579810f8e5abb6c329f1a688bd42e2feddc8a</signature></skey><device-identity><!-- 148 bytes --></device-identity></keys></receipt>
17:40:50.752 [Client/Recv DEBUG] <ack class="receipt" from="19148****@s.whatsapp.net" id="E057347129E155279DBE6A7DA114BBA7" type="retry"/>
17:40:50.752 [Client/Recv DEBUG] <notification from="19148****@s.whatsapp.net" id="3870335523" t="1663868449" type="privacy_token"><tokens><token jid="7535***06@s.whatsapp.net" t="1663868449" type="trusted_contact">01016204115252ab63732cbe4fd0a6cf0dae3041d1049d18ebd8670765e2cc82378a5f</token></tokens></notification>
17:40:50.752 [Client/Send DEBUG] <ack class="notification" id="3870335523" to="19148****@s.whatsapp.net" type="privacy_token"/>
17:41:55.802 [Client/Recv DEBUG] <message from="19148****@s.whatsapp.net" id="D259768B4998BD7347FFED3E45712269" notify="*MaskedPushName**" t="1663868515" type="media"><enc mediatype="ptt" type="pkmsg" v="2"><!-- 648 bytes --></enc></message>
17:41:55.802 [Client/Send DEBUG] <ack class="message" id="D259768B4998BD7347FFED3E45712269" to="19148****@s.whatsapp.net"/>
17:41:55.813 [Client/Send DEBUG] <receipt id="D259768B4998BD7347FFED3E45712269" to="19148****@s.whatsapp.net" type="inactive"/>

```

**Comment by tulir** [comment] 2022-09-24 08:23
Duplicate of #161

**Closed by tulir** 2022-09-24 08:23 UTC

**Comment by 1337-sys** [comment] 2022-09-25 18:10
If I call **sendRetryReceipt** function for that message id every few minutes, can I decrypt the message?

**Comment by tulir** [comment] 2022-09-25 18:13
No, retry receipts are sent automatically (as you can see in your log `[Client/Send DEBUG] <receipt ... type="retry">...`)

**Comment by 1337-sys** [comment] 2022-09-25 20:02
Yeah i saw it. There was no  incoming  message at that time. Will it work if I call it every 5-10 minutes? Web whatsapp decrypt this message after a while. I thought it was constantly sending retry for the corresponding message id in the background.
