### ISSUE TITLE
Waiting for this message issue in IPhone . 

### ISSUE THREAD

**Issue by bhavesh53** [tulir/whatsmeow#205] opened 2022-07-18 06:47 UTC
Getting problem in Iphone Device when sending message .for android is working fine .

![WhatsApp Image 2022-07-18 at 11 59 31 AM](https://user-images.githubusercontent.com/1794741/179457269-2e5fecbc-85be-47b3-9dc1-009bea17b034.jpeg)

**Comment by tulir** [comment] 2022-07-18 07:32
Duplicate of #160

**Closed by tulir** 2022-07-18 07:32 UTC

**Comment by elpulga** [comment] 2022-07-18 13:40
Is there a way to detect when this happens ?
